### ISSUE TITLE
Optionen für Subscribe Button / Wahl der Größe

### ISSUE THREAD

**Issue by rsieber** [podlove/podlove-subscribe-button-wp-plugin#1]
Hallo,

ist echt eine Klasse-Idee der Button!!

Wie kann ich dem Shortcode beibringen, welches Format er anzeigen soll. Auf Eurer Testseite sind verschiedene Format zu sehen.

Danke!

Robert

**Comment by chemiker** [comment]
Hallo Robert,

das Plugin ist mittlerweile im Wordpress.org Repo verfügbar, falls du es noch gebrauchen kannst: https://wordpress.org/plugins/podlove-subscribe-button/
