### ISSUE TITLE
Spracheinstellungen werden ignoriert

### ISSUE THREAD

**Issue by markusvoelter** [podlove/podlove-subscribe-button-wp-plugin#11]
Ich versuche, einem der drei Subscribe-Buttons auf der Webseite das deutsche "Abonnieren" beizubringen statt dem Subscribe. Funktioniert aber nicht, alles haben "Subscribe" als Titel.

![screen shot 2016-06-11 at 13 44 40](https://cloud.githubusercontent.com/assets/592330/15985187/a66001aa-2fe5-11e6-95f2-a9d47db53acb.png)

![screen shot 2016-06-11 at 13 44 48](https://cloud.githubusercontent.com/assets/592330/15985188/aec94158-2fe5-11e6-99a5-19f477bd6ca8.png)

Benutzung per Shortcode im Widget:

![screen shot 2016-06-11 at 13 45 29](https://cloud.githubusercontent.com/assets/592330/15985191/ba23f9c6-2fe5-11e6-81a3-20f9da560895.png)

**Comment by benzimmer** [comment]
Laut readme/code kennt das Plugin den Parameter `language` gar nicht und reicht ihn daher auch nicht an das Button Javascript weiter.

**Comment by markusvoelter** [comment]
Aha, das heißt ich habe aus der Doku des Publishers fälschlicherweise geschlossen, dass dieses andere Button den Parameter auch kann.

**Comment by chemiker** [comment]
Ja, das ist korrekt. Im Plugin wird diese Option noch nicht unterstützt. Für die Zwischenzeit hilft es dir vllt., dass immer der Language Code aus WordPress übernommen wird. Sprich bei einer deutschen WordPress Installation hast du dann auch einen deutschen Button.

**Comment by markusvoelter** [comment]
Das hilft mir leider nicht, denn ich brauche verschiedene Sprachen auf
derselben Webseite.
​

**Comment by timpritlove** [comment]
@chemiker könntest du das ggf. kurzfristig nachreichen? sprache ist wichtig

**Comment by chemiker** [comment]
Kurzes Update: Version 1.3 steht kurz vor der Vollendung und sollte zeitnahe released werden. Ab dann wird oben genutzter Shortcode funktionieren.

**Comment by markusvoelter** [comment]
Super, @chemiker. Das gilt dann auch für die Standalone-Version des Buttons, und nicht nur für das Release als Teil des Publishers, richtig?

**Comment by chemiker** [comment]
@markusvoelter Ja. Es geht um das Standalone WordPress Plugin.
