### ISSUE TITLE
Handing over to PocketCasts goes to an invalid URL

### ISSUE THREAD

**Issue by grantbarrett** [podlove/podlove-subscribe-button-wp-plugin#12]
The PocketCasts handoff sends to 

http://pcasts.in/feed/{somefeedhost}

but a 404 occurs.

**Comment by timpritlove** [comment]
This a long-standing bug in PocketCasts, not looking up the feed when it is not already in its database.

**Comment by grantbarrett** [comment]
Well, I hope it can be fixed, especially now that PocketCasts has been bought by a group including NPR and is likely to be getting a lot more adoption.

**Comment by cfoellmann** [comment]
The repo of the actual script https://github.com/podlove/podlove-subscribe-button might be the better place for this, right?

Is this related to these issues? https://github.com/podlove/podlove-subscribe-button/issues?utf8=%E2%9C%93&q=is%3Aissue+pocketcast

**Comment by eteubert** [comment]
Duplicate of https://github.com/podlove/podlove-subscribe-button/issues/112 but yes, the issue should not be tracked in the WP repo anyway.
