### ISSUE TITLE
Kann keinen Button anlegen

### ISSUE THREAD

**Issue by henningkrause** [podlove/podlove-subscribe-button-wp-plugin#5]
Beim Button anlegen, kriege ich immer eine Fehlermeldung, die mir so aussieht, als sei da ein URL-Pfad falsch gesetzt, siehe https://twitter.com/henningkrause/status/603116966459613187

**Comment by timpritlove** [comment]
Kannst du die URL die da im Browser steht mal hier komplett reinpasten? Ist im Screenshot abgeschnitten.

**Comment by henningkrause** [comment]
Hmm, kann ich leider nicht, da ich diesen Fehler so nun nicht mehr reproduzieren kann. Wenn ich nun einen neuen Button anlegen will, lande ich nach dem Klick auf "Save Changes" einfach wieder auf /wp-admin/network/settings.php?page=podlove-subscribe-button - erstaunlich.

Was mir aber nun auffiel: Das Ganze findet in einem WP-Multisite-Netzwerk auf Unterverzeichnisbasis statt. Ich hatte versucht, den Button im Subblog "Augenspiegel" (https://blogs.helmholtz.de/augenspiegel/wp-admin/options-general.php?page=podlove-subscribe-button) anzulegen, wo ich ihn auch verwenden wollte. Nach der Fehlermeldung habe ich nun aber gesehen, dass der Subscribe-Button für den Sternengeschichten-Podcast in der Netzwerk-Verwaltung des Wordpress' angelegt wurde (https://blogs.helmholtz.de/wp-admin/network/settings.php?page=podlove-subscribe-button). Allerdings kann ich ihn mit [podlove-subscribe-button button="Sternengeschichten"] nicht im Augenspiegel-Subblog ansprechen.

**Comment by chemiker** [comment]
Kannst du denn den Button jetzt in Subblog anlegen, oder klappt das nicht?

**Comment by henningkrause** [comment]
Nein, da passiert das oben Beschriebene: da lande ich nach dem Klick auf "Save Changes" einfach wieder auf /wp-admin/network/settings.php?page=podlove-subscribe-button

**Comment by chemiker** [comment]
Aber du hast doch geschrieben, dass als du in deinem Subblog einen Button angelegt hast, jener auch gespeichert wurde. Allerdings auch Netzwerkeebene. Oder habe ich das falsch verstanden?

**Comment by henningkrause** [comment]
Das hast Du richtig verstanden. Wenn ich probiere, den Button auf Netzwerk-Ebene anzulegen, dann werde ich auf die URL https://blogs.helmholtz.de/wp-admin/wp-admin/network/settings.php?page=podlove-subscribe-button&button=4&action=edit&network=1 weitergeleitet und das gibt eine Fehlermeldung. Das ist o.g. URL, die ich zunächst nicht reproduzieren konnte.

**Comment by timpritlove** [comment]
Da ist definitiv ein `wp-admin/`zu viel :)

**Comment by chemiker** [comment]
In der Tat. Fragt sich nur: Wieso? Liegt sicherlich an der Zeile hier: https://github.com/podlove/podlove-subscribe-button-wp-plugin/blob/master/settings/buttons.php#L98

Ich frage mich nur, wieso das Lokal nicht auftritt…

**Comment by henningkrause** [comment]
Ja, und das Ganze geht nur im zentralen Blog des Netzwerks auf Unterzeichnis-Basis. Und diese Buttons kann ich dann aber in einem Subblog nicht einbinden. Und in den Subblogs kann ich keinen Button anlegen. Da kommt gar keine Fehlermeldung. Es wird aber auch dort kein Button abgespeichert.

Habt ihr das schonmal in einer Testinstanz als Multisite-Netzwerk in Unterverzeichnis-Variante ausprobiert?

**Comment by chemiker** [comment]
Ja, haben wir. Wir haben das sogar aktiv im Einsatz. Daher wundert mich gerade ein wenig, warum das bei dir Fehler wirft.

Kannst du mir zufälligerweise sagen, welche WordPress und PHP Version du im Einsatz hast?

**Comment by henningkrause** [comment]
Das Wordpress ist das aktuelle 4.2.2. PHP war bis eben gerade 5.4. Ich habe dann mal auf 5.6.6. umgestellt. Das ändert allerdings auch nichts.

Und das Problem mit dem doppelten "wp-admin/" kann nicht die Ursache sein?

**Comment by chemiker** [comment]
Naja, könnte schon. Das Problem ist, dass ich das doppelte wp-admin/ zwar reproduzieren kann, jedoch die Buttons trotzdem abgespeichert werden.

**Comment by chemiker** [comment]
In den nächsten Minuten sollte bei dir ein Update für das Plugin erscheinen. Schau mal bitte, ob das dein Problem löst. Zumindest sollte kein doppeltes wp-admin/ mehr auftauchen…

**Comment by timpritlove** [comment]
Update ist jetzt verfügbar und sollte das Problem lösen.

**Comment by henningkrause** [comment]
Ich habe es jetzt nochmal bei uns ausprobiert und es klappt leider immer noch nicht. Ich kann in dem Blognetzwerk (WP-Multisite) auf Unterverzeichnis-Basis nur im zentralen Blog Subscribe-Buttons anlegen, aber nicht in dem Subblog, in dem ich das eigentlich verwenden will. Von dem Subblog aus kann ich den Subscribe-Button im zentralen Blog aber nicht einbinden ("ID nicht gefunden"). Beim Versuch, den Button im Subblog anzulegen, passiert nach dem Klick auf "Save" nur ein Neuladen der Setting-Seite, aber es ist danach kein Button vorhanden.

**Comment by henningkrause** [comment]
Das kann ich nicht sagen. Ich habe das Subscribe-Button-Plugin dann irgendwann Ende 2015 in dem Wordpress deinstalliert. Und dachte mir, nachdem hier auch nix mehr passierte: Dann hat https://blogs.helmholtz.de/augenspiegel/2014/03/wissenschaft-auf-die-ohren-audiopodcasts/ halt keine Subscribe-Buttons bei den ganzen verlinkten Podcasts. Aber mittlerweile gibt es ja wissenschaftspodcasts.de und das ist ja ne single site-Installation von WP und da klappt es ja auch mit den Subscribe buttons.

**Comment by chemiker** [comment]
ok. Danke für die Rückmeldung.
