### ISSUE TITLE
Plugin uses wrong source for plugin JS

### ISSUE THREAD

**Issue by benzimmer** [podlove/podlove-subscribe-button-wp-plugin#6]
Please do not use docs.podlove.org for integrating the button as this is the development testing version. Please use cdn.podlove.org as shown in the [buttons readme](https://github.com/podlove/podlove-subscribe-button#using-the-podlove-cdn).

Original issue here: https://github.com/podlove/podlove-subscribe-button/issues/67

**Comment by chemiker** [comment]
Should be fixed with the recent release.
